config/routes.rb
Rails.application.routes.draw do

  resources :bio_changes

  resources :relationships

  resources :users do
    member do
      get 'bio_change_count'
    end
    # collection do
    #   get 'all_bio_changes'
    # end
  end

  get 'sign_up' => "users#new", as: 'sign_up'

  resources :sessions, only:[:new, :create, :destroy]
  get 'login' => "sessions#new", as: 'login'
  get 'logout' => "sessions#destroy", as: 'logout'

  root 'welcome#index'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :followed, class_name: 'User', counter_cache: :followers_count
  belongs_to :follower, class_name:'User', counter_cache: :followeds_count
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  def index
    @relationships = Relationship.page(params[:page])
    respond_with @relationships
  end

  def show
    respond_with @relationship
  end

  def new
    @relationship = Relationship.new
  end

  def edit
  end

  def create
    @relationship = Relationship.new(relationship_params)

    respond_with do |format|
      if @relationship.save
        @user = @relationship.followed
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render json: @relationship, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
        format.js {head :unprocessable_entity}
      end
    end
  end

  def update
    respond_with do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
        format.js {head :unprocessable_entity}
      end
    end
  end

  def destroy
    @user = @relationship.followed
    @relationship.destroy
    respond_with do |format|
      format.html { redirect_to relationships_url }
      format.json { head :no_content }
    end
  end

  private
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    def relationship_params
      params.require(:relationship).permit(:follower_id, :followed_id)
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.haml
= simple_form_for(@relationship) do |f|
  = f.error_notification

  .form-inputs
    = f.association :follower
    = f.association :followed

  .form-actions
    = f.button :submit

app/views/relationships/edit.html.haml
.page-header
  = link_to relationships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @relationship, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing relationship

= render 'form'

app/views/relationships/index.html.haml
.page-header
  = link_to new_relationship_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Relationship
  %h1 Listing relationships

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Follower
        %th Followed
        %th
        %th
        %th

    %tbody
      - @relationships.each do |relationship|
        %tr
          %td= relationship.follower
          %td= relationship.followed
          %td= link_to 'Show', relationship
          %td= link_to 'Edit', edit_relationship_path(relationship)
          %td= link_to 'Destroy', relationship, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/relationships/new.html.haml
.page-header
  = link_to relationships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New relationship

= render 'form'

app/views/relationships/show.html.haml
.page-header
  = link_to relationships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_relationship_path(@relationship), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show relationship

%dl.dl-horizontal
  %dt Follower:
  %dd= @relationship.follower
  %dt Followed:
  %dd= @relationship.followed