config/routes.rb
Rails.application.routes.draw do

  resources :bio_changes

  resources :relationships

  resources :users do
    member do
      get 'bio_change_count'
    end
    # collection do
    #   get 'all_bio_changes'
    # end
  end

  get 'sign_up' => "users#new", as: 'sign_up'

  resources :sessions, only:[:new, :create, :destroy]
  get 'login' => "sessions#new", as: 'login'
  get 'logout' => "sessions#destroy", as: 'logout'

  root 'welcome#index'

end

app/models/bio_change.rb
class BioChange < ActiveRecord::Base
  belongs_to :user, counter_cache: :bio_update_count

  default_scope ->{order(created_at: :desc)}
  scope :for_user, ->(user){ where(user:user.followed_users) if user}
end

app/controllers/bio_changes_controller.rb
class BioChangesController < ApplicationController
  before_action :set_bio_change, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def index
    @bio_changes = BioChange.for_user(current_user).includes(:user).page(params[:page])
    respond_with @bio_changes do  |format|
      format.json {render json: BioChange.includes(:user).page(params[:page])}
    end
  end

  def show
    respond_with @bio_change
  end

  def new
    @bio_change = BioChange.new
  end

  def edit
  end

  def create
    @bio_change = BioChange.new(bio_change_params)

    respond_with do |format|
      if @bio_change.save
        format.html { redirect_to @bio_change, notice: 'Bio change was successfully created.' }
        format.json { render json: @bio_change, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @bio_change.errors, status: :unprocessable_entity }
        format.js {head :unprocessable_entity}
      end
    end
  end

  def update
    respond_with do |format|
      if @bio_change.update(bio_change_params)
        format.html { redirect_to @bio_change, notice: 'Bio change was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bio_change.errors, status: :unprocessable_entity }
        format.js {head :unprocessable_entity}
      end
    end
  end

  def destroy
    @bio_change.destroy
    respond_to do |format|
      format.html { redirect_to bio_changes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_bio_change
      @bio_change = BioChange.find(params[:id])
    end

    def bio_change_params
      params.require(:bio_change).permit(:user_id, :content)
    end
end

app/helpers/bio_changes_helper.rb
module BioChangesHelper
end

app/views/bio_changes/_form.html.haml
= simple_form_for(@bio_change) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :content

  .form-actions
    = f.button :submit

app/views/bio_changes/edit.html.haml
.page-header
  = link_to bio_changes_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @bio_change, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing bio_change

= render 'form'

app/views/bio_changes/index.html.haml
.page-header
  = link_to new_bio_change_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Bio change
  %h1 Listing bio_changes

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th User
        %th Content
        %th
        %th
        %th
        %th Created_at

    %tbody
      - @bio_changes.each do |bio_change|
        %tr
          %td=link_to bio_change.user.name, bio_change.user
          %td= bio_change.content
          %td= link_to 'Show', bio_change
          %td= link_to 'Edit', edit_bio_change_path(bio_change)
          %td= link_to 'Destroy', bio_change, :data => { confirm: 'Are you sure?' }, :method => :delete
          %td= bio_change.created_at

app/views/bio_changes/new.html.haml
.page-header
  = link_to bio_changes_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New bio_change

= render 'form'

app/views/bio_changes/show.html.haml
.page-header
  = link_to bio_changes_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_bio_change_path(@bio_change), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show bio_change

%dl.dl-horizontal
  %dt User:
  %dd= @bio_change.user
  %dt Content:
  %dd= @bio_change.content