config/routes.rb
Rails.application.routes.draw do

  resources :bio_changes

  resources :relationships

  resources :users do
    member do
      get 'bio_change_count'
    end
    # collection do
    #   get 'all_bio_changes'
    # end
  end

  get 'sign_up' => "users#new", as: 'sign_up'

  resources :sessions, only:[:new, :create, :destroy]
  get 'login' => "sessions#new", as: 'login'
  get 'logout' => "sessions#destroy", as: 'logout'

  root 'welcome#index'

end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
    %button.close{:type => "button", :data => {:dismiss => "alert"} }
      %span{:aria => {:hidden => "true"} } &times;
      %span.sr-only Close
    = msg

app/views/layouts/_head.html.haml
%head
  %meta{:charset => "utf-8"}
  %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %meta{:content => "", :name => "description"}
  %meta{:content => "", :name => "author"}
  %title= content_for?(:title) ? yield(:title) : "bio update app"

  / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
  /[if lt IE 9]
    = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Project name", root_path, class:"navbar-brand"
    #navbar.collapse.navbar-collapse
      = yield

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    = render layout:'layouts/navbar' do
      %ul.nav.navbar-nav
        %li.active=link_to 'Home', root_path
        - if current_user
          %li=link_to 'users', users_path
          %li=link_to 'bio_changes', bio_changes_path
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to "Profile #{current_user.name}", current_user
          %li= link_to "Logout", logout_path
        - else
          %li= link_to "Sign Up", sign_up_path
          %li= link_to "Login", login_path

    .container
      = render 'layouts/flash'
      = yield